name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 0 * * *' }]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: { branches: ['master', 'main'] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: stats
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: stats.svg
          user: knutfr
          template: repository
          base: header, activity, community, repositories, metadata
          config_display: regular
          config_timezone: Europe/Paris
